const CAT_ICONS={sight:'◆',building:'▥',view:'⌃',cafe:'☕',food:'●',bar:'♪',activity:'✦',architecture:'⌂',walk:'↝',market:'▦',district:'◇',memorial:'†',wc:'WC'};
const map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([47.4979,19.0552],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomleft'}).addTo(map);
const $=s=>document.querySelector(s);const els={sheet:$('#sheet'),handle:$('#handle'),sheetHead:$('#sheetHead'),title:$('#title'),sub:$('#sub'),content:$('#content'),context:$('#context'),contextSymbol:$('#contextSymbol'),toast:$('#toast'),modalBackdrop:$('#modalBackdrop'),modal:$('#modal'),navCard:$('#navCard'),navTitle:$('#navTitle'),navMeta:$('#navMeta'),navArrow:$('#navArrow'),mapView:$('#mapView'),guideView:$('#guideView'),guideContent:$('#guideContent')};
const state={places:[],markers:new Map(),selected:null,panel:'mini',view:'map',navLine:null,dayRoutes:[],activeGuideDay:1};const P={mini:112,peek:176,half:()=>Math.round(innerHeight*.52),full:()=>Math.round(innerHeight*.91)};const h=s=>typeof P[s]==='function'?P[s]():P[s];
function toast(t){els.toast.textContent=t;els.toast.classList.add('show');clearTimeout(els.toast.t);els.toast.t=setTimeout(()=>els.toast.classList.remove('show'),1400)}function get(id){return state.places.find(p=>p.id===id)}
function markerIcon(p,sel=false){return L.divIcon({className:'',html:`<div class="tc-wrap ${p.cat} ${sel?'selected':''}"><div class="tc-pin"><span class="tc-icon">${CAT_ICONS[p.cat]||'•'}</span></div></div>`,iconSize:[38,43],iconAnchor:[19,43]})}
function setPanel(name,animate=true){state.panel=name;document.documentElement.style.setProperty('--sheet-h',h(name)+'px');els.sheet.style.transition=animate?'height .38s cubic-bezier(.22,.9,.24,1)':'none';els.sheet.style.height=h(name)+'px'}
function updateMarkers(){state.markers.forEach((m,id)=>m.setIcon(markerIcon(get(id),id===state.selected)))}
function detailHTML(p){return `<div class="detail-grid"><div class="metric"><b>${p.duration} p</b>Idő</div><div class="metric"><b>${p.price}</b>Ár</div><div class="metric"><b>${p.day}. nap</b>Program</div></div><p class="description">${p.desc}</p><div class="card"><div class="card-main"><b>Megéri?</b><span>${p.worth}</span></div></div><div class="quick"><button class="chip" id="internalNav">➤ Navigáció az appban</button><button class="chip" id="openGuidePlace">📖 Útikalauzban</button></div>`}
function selectPlace(id){state.selected=id;updateMarkers();const p=get(id);map.flyTo([p.lat,p.lon],Math.max(map.getZoom(),15),{duration:.45});els.title.textContent=p.name;els.sub.textContent=`${p.label} · ${p.duration} perc`;els.content.innerHTML=detailHTML(p);$('#internalNav').onclick=()=>startNavigation(p);$('#openGuidePlace').onclick=()=>switchView('guide',p.day,p.id);setPanel('peek')}
function card(p){return `<div class="card" data-id="${p.id}"><div class="thumb"></div><div class="card-main"><b>${p.order}. ${p.name}</b><span>${p.label} · ${p.duration} perc</span></div><button class="icon-btn" data-nav="${p.id}">➤</button></div>`}
function bindCards(){document.querySelectorAll('[data-id]').forEach(c=>c.onclick=e=>{if(!e.target.closest('[data-nav]'))selectPlace(c.dataset.id)});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=e=>{e.stopPropagation();startNavigation(get(b.dataset.nav))});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>showDay(+b.dataset.day))}
function renderPlan(){els.content.innerHTML=`<div class="daytabs">${[1,2,3].map(d=>`<button data-day="${d}">${d}. nap</button>`).join('')}</div>`+[1,2,3].map(d=>`<h3>${d}. nap</h3>${state.places.filter(p=>p.day===d&&p.cat!=='wc').sort((a,b)=>a.order-b.order).map(card).join('')}`).join('');bindCards()}
function resetPanel(){state.selected=null;updateMarkers();els.title.textContent='Budapest tesztútiterv';els.sub.textContent='3 laza nap · 24 hely';renderPlan();setPanel('mini')}
function showDay(day){state.selected=null;updateMarkers();const arr=state.places.filter(p=>p.day===day&&p.cat!=='wc').sort((a,b)=>a.order-b.order);els.title.textContent=`${day}. nap`;els.sub.textContent=`${arr.length} hely · laza budapesti program`;els.content.innerHTML=`<div class="daytabs">${[1,2,3].map(d=>`<button class="${d===day?'active':''}" data-day="${d}">${d}. nap</button>`).join('')}</div>${arr.map(card).join('')}`;bindCards();setPanel('half');const fg=L.featureGroup(arr.map(p=>state.markers.get(p.id)));map.fitBounds(fg.getBounds(),{paddingTopLeft:[30,90],paddingBottomRight:[30,Math.round(innerHeight*.45)]})}
function renderGuide(day=1,focusId=null){state.activeGuideDay=day;document.querySelectorAll('[data-guide-day]').forEach(b=>b.classList.toggle('active',+b.dataset.guideDay===day));const arr=state.places.filter(p=>p.day===day&&p.cat!=='wc').sort((a,b)=>a.order-b.order);els.guideContent.innerHTML=`<h2>${day}. nap</h2>${arr.map(p=>`<article class="guide-place" id="guide-${p.id}"><div class="guide-num">${p.order}</div><div><h3>${p.name}</h3><p>${p.desc}</p><div class="guide-meta">${p.label} · ${p.duration} perc · ${p.price}</div><div class="guide-actions"><button data-map-place="${p.id}">Térképen</button><button data-guide-nav="${p.id}">Navigáció</button></div></div></article>`).join('')}`;document.querySelectorAll('[data-map-place]').forEach(b=>b.onclick=()=>{switchView('map');selectPlace(b.dataset.mapPlace)});document.querySelectorAll('[data-guide-nav]').forEach(b=>b.onclick=()=>startNavigation(get(b.dataset.guideNav)));if(focusId)setTimeout(()=>document.querySelector(`#guide-${focusId}`)?.scrollIntoView({behavior:'smooth',block:'center'}),120)}
function switchView(view,day=state.activeGuideDay,focusId=null){state.view=view;const guide=view==='guide';els.mapView.classList.toggle('active',!guide);els.guideView.classList.toggle('active',guide);els.guideView.setAttribute('aria-hidden',String(!guide));els.sheet.classList.toggle('hidden',guide);els.context.classList.toggle('guide-mode',guide);els.contextSymbol.textContent=guide?'🗺':'📖';if(guide)renderGuide(day,focusId);else setTimeout(()=>map.invalidateSize(),320)}
function showAI(){els.title.textContent='3 Companion-javaslat';els.sub.textContent='Finom, nem tolakodó segítség';els.content.innerHTML=`<div class="card"><div class="card-main"><b>☔ Délután eső várható</b><span>A Gellért-hegyet érdemes előrébb hozni.</span></div></div><div class="card"><div class="card-main"><b>🚻 WC 180 méterre</b><span>Nyitott utility pont.</span></div></div><div class="card"><div class="card-main"><b>☕ Nyugodtabb kávézó</b><span>8 perc kitérő.</span></div></div>`;setPanel('half')}
async function buildDayRoute(day){const pts=state.places.filter(p=>p.day===day&&p.cat!=='wc').sort((a,b)=>a.order-b.order);const coords=pts.map(p=>`${p.lon},${p.lat}`).join(';');try{const r=await fetch(`https://router.project-osrm.org/route/v1/foot/${coords}?overview=full&geometries=geojson`);if(!r.ok)throw 0;const data=await r.json();const rt=data.routes?.[0];if(!rt)throw 0;const latlngs=rt.geometry.coordinates.map(c=>[c[1],c[0]]);state.dayRoutes.push(L.polyline(latlngs,{color:{1:'#c8102e',2:'#4da3ff',3:'#45c56f'}[day],weight:4,opacity:.72}).addTo(map))}catch{state.dayRoutes.push(L.polyline(pts.map(p=>[p.lat,p.lon]),{color:{1:'#c8102e',2:'#4da3ff',3:'#45c56f'}[day],weight:3,opacity:.55,dashArray:'10 8'}).addTo(map))}}
function bearing(a,b){const φ1=a.lat*Math.PI/180,φ2=b.lat*Math.PI/180,Δλ=(b.lng-a.lng)*Math.PI/180;return(Math.atan2(Math.sin(Δλ)*Math.cos(φ2),Math.cos(φ1)*Math.sin(φ2)-Math.sin(φ1)*Math.cos(φ2)*Math.cos(Δλ))*180/Math.PI+360)%360}
function updateNav(from,target,d){d=d??map.distance(from,[target.lat,target.lon]);els.navArrow.style.transform=`rotate(${bearing(from,L.latLng(target.lat,target.lon))}deg)`;els.navTitle.textContent=target.name;els.navMeta.textContent=`${d<1000?Math.round(d)+' m':(d/1000).toFixed(1)+' km'} · kb. ${Math.max(1,Math.round(d/80))} perc`;els.navCard.classList.add('show')}
async function routeFrom(from,target){if(state.navLine)map.removeLayer(state.navLine);try{const r=await fetch(`https://router.project-osrm.org/route/v1/foot/${from.lng},${from.lat};${target.lon},${target.lat}?overview=full&geometries=geojson`);const data=await r.json();const rt=data.routes?.[0];if(!rt)throw 0;state.navLine=L.polyline(rt.geometry.coordinates.map(c=>[c[1],c[0]]),{color:'#c8102e',weight:6,opacity:.92}).addTo(map);map.fitBounds(state.navLine.getBounds(),{paddingTopLeft:[25,150],paddingBottomRight:[25,h(state.panel)+30]});updateNav(from,target,rt.distance)}catch{state.navLine=L.polyline([from,[target.lat,target.lon]],{color:'#c8102e',weight:5,dashArray:'10 8'}).addTo(map);updateNav(from,target)}}
function startNavigation(target){switchView('map');const use=ll=>routeFrom(ll,target);navigator.geolocation?.getCurrentPosition(p=>use(L.latLng(p.coords.latitude,p.coords.longitude)),()=>use(map.getCenter()),{enableHighAccuracy:true,timeout:5000})||use(map.getCenter())}
function stopNavigation(){if(state.navLine){map.removeLayer(state.navLine);state.navLine=null}els.navCard.classList.remove('show')}
function showVersions(){els.modal.innerHTML=`<h2>Alpha-verziók</h2><a class="version" href="versions/v0.1/index.html">Alpha v0.1</a><a class="version" href="versions/v0.2/index.html">Alpha v0.2 · Budapest</a><a class="version" href="index.html">Alpha v0.3</a><a class="version current" href="index.html">Alpha v0.3.1 · Guide View</a><button class="chip" id="closeModal">Bezárás</button>`;els.modalBackdrop.classList.add('show');$('#closeModal').onclick=()=>els.modalBackdrop.classList.remove('show')}
function initGestures(){let drag=null;function begin(e){if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,startH:els.sheet.getBoundingClientRect().height,lastX:e.clientX,lastY:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId);els.sheet.classList.add('dragging')}function move(e){if(!drag)return;e.preventDefault();drag.lastX=e.clientX;drag.lastY=e.clientY;if(Math.abs(e.clientX-drag.x)>Math.abs(e.clientY-drag.y))return;const hh=Math.max(P.mini,Math.min(innerHeight*.94,drag.startH+drag.y-e.clientY));document.documentElement.style.setProperty('--sheet-h',hh+'px');els.sheet.style.height=hh+'px'}function end(){if(!drag)return;const dx=drag.lastX-drag.x,dy=drag.y-drag.lastY,hh=els.sheet.getBoundingClientRect().height;drag=null;els.sheet.classList.remove('dragging');if(Math.abs(dx)>70){switchView(dx<0?'guide':'map');return}if(dy<-28){setPanel('mini');return}if(dy>28){if(hh<h('half')-30)setPanel('half');else setPanel('full');return}const choices=state.selected?['peek','half','full']:['mini','half','full'];let best=choices[0],dist=1e9;choices.forEach(s=>{const d=Math.abs(h(s)-hh);if(d<dist){dist=d;best=s}});setPanel(best)}[els.handle,els.sheetHead].forEach(z=>{z.addEventListener('pointerdown',begin);z.addEventListener('pointermove',move,{passive:false});z.addEventListener('pointerup',end);z.addEventListener('pointercancel',end)})}
async function init(){state.places=await fetch('data/budapest.json').then(r=>r.json());state.places.forEach(p=>{const m=L.marker([p.lat,p.lon],{icon:markerIcon(p)}).addTo(map);m.on('click',()=>selectPlace(p.id));state.markers.set(p.id,m)});await Promise.all([1,2,3].map(buildDayRoute));renderPlan();renderGuide(1);setPanel('mini',false);initGestures();map.on('click',()=>state.selected?resetPanel():setPanel('mini'))}
els.context.onclick=()=>switchView(state.view==='map'?'guide':'map');$('#insightStrip').onclick=showAI;document.querySelectorAll('[data-guide-day]').forEach(b=>b.onclick=()=>renderGuide(+b.dataset.guideDay));$('#guideVersions').onclick=showVersions;$('#locate').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{map.setView([p.coords.latitude,p.coords.longitude],16);toast('Aktuális hely megjelenítve')},()=>toast('A helyzet nem érhető el'),{enableHighAccuracy:true});$('#stopNav').onclick=stopNavigation;els.modalBackdrop.onclick=e=>{if(e.target===els.modalBackdrop)els.modalBackdrop.classList.remove('show')};window.addEventListener('resize',()=>setPanel(state.panel,false));init();
